const products = [
    {
        id: 1,
        name: "iPhone 13",
        desc: "The latest iPhone with advanced features.",
        price: 999.99,
        image: "https://images.unsplash.com/photo-1604054923518-e491a9a6afbb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1480&q=80",
        rating: 4.7,
    },
    {
        id: 2,
        name: "Samsung Galaxy S21",
        desc: "A powerful Android smartphone from Samsung.",
        price: 899.99,
        image: "galaxyS21.jpg",
        rating: 4.6,
    },
    {
        id: 3,
        name: "Google Pixel 6",
        desc: "Google's flagship phone with exceptional camera capabilities.",
        price: 799.99,
        image: "https://m.media-amazon.com/images/I/41W0dAnmX9L._SX300_SY300_QL70_FMwebp_.jpg",
        rating: 4.8,
    },
    {
        id: 4,
        name: "OnePlus 9 Pro",
        desc: "A high-performance smartphone from OnePlus.",
        price: 899.99,
        image: "https://m.media-amazon.com/images/I/41W0dAnmX9L._SX300_SY300_QL70_FMwebp_.jpg",
        rating: 4.6,
    },
    {
        id: 5,
        name: "Xiaomi Mi 11",
        desc: "A feature-packed phone from Xiaomi.",
        price: 699.99,
        image: "https://m.media-amazon.com/images/I/41eSQvTbsaL._SX300_SY300_QL70_FMwebp_.jpg",
        rating: 4.5,
    },
    {
        id: 6,
        name: "Sony Xperia 1 III",
        desc: "A premium Xperia phone with a 4K display.",
        price: 1099.99,
        image: "https://m.media-amazon.com/images/I/31MFIOE6G7L._SX300_SY300_QL70_FMwebp_.jpg",
        rating: 4.7,
    },
    {
        id: 7,
        name: "LG V70 ThinQ",
        desc: "LG's flagship phone with advanced camera technology.",
        price: 799.99,
        image: "https://m.media-amazon.com/images/I/41jJ6IgYY0L._SX300_SY300_QL70_FMwebp_.jpg",
        rating: 4.4,
    },
    {
        id: 8,
        name: "Motorola Moto G Power (2021)",
        desc: "A budget-friendly phone with long battery life.",
        price: 249.99,
        image: "https://m.media-amazon.com/images/I/31+wP8CU+LL._SY300_SX300_.jpg",
        rating: 4.2,
    },
    {
        id: 9,
        name: "Asus ROG Phone 5",
        desc: "A gaming phone designed for high-performance gaming.",
        price: 899.99,
        image: "https://m.media-amazon.com/images/I/51dPfdDD0wL._SX300_SY300_QL70_FMwebp_.jpg",
        rating: 4.8,
    },
    {
        id: 10,
        name: "Huawei P40 Pro",
        desc: "Huawei's flagship phone with advanced camera technology.",
        price: 899.99,
        image: "https://m.media-amazon.com/images/I/41GHiSkx3GL._SX300_SY300_QL70_FMwebp_.jpg",
        rating: 4.5,
    },
];


module.exports = products;